name: pyhpc-bench-cpu
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>3.6,<3.9
  - pip
  - pip:
    - click
    - aesara
    - numba
    - torch>=1.10
    - tensorflow>=2.0
    - -f https://storage.googleapis.com/jax-releases/jax_releases.html
    - jax[cpu]
